name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.Docker_Username }}
          password: ${{ secrets.Docker_Passwd }}

      - name: Build the Docker image
        run: docker build . -t alihussnain901/devops-task:latest

      - name: Push the Docker image
        run: docker push alihussnain901/devops-task:latest
